### ISSUE TITLE
No google chrome store page :(

### ISSUE THREAD

**Issue by CortexReaver** [gil/DownFlickr#6]
Hello, where I can download your plugin? Seems it was deleted from the google chrome store and there is no releases on github.

**Comment by gil** [comment]
Hey @CortexReaver ! I haven't used or updated this extension in many years now, so there's a big chance it's not even working anymore.

You can try to download the source and add to your Chrome and see if it still works, maybe it does, or maybe it'll require some fixes to get it back working. When you open Chrome's extension page, there's a button "Load unpacked" that you can point to the directory where the source code is and it'll install it. Hope it helps 😀

**Comment by CortexReaver** [comment]
Yeah, thanks for the answer. I wrote this because I cannot find any plugin like this, for quick downloading pictures from flickr. There was only one for Firefox and that's it. Maybe because all these plugins was deleted from chrome store of legal issues (allowing you to download copyrighted pictures), idk. But I hope you or someone else will continue the work on such plugin.
